"""create_spy_cat_table

Revision ID: 722fc001fbc4
Revises: 
Create Date: 2025-08-30 15:07:40.958969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722fc001fbc4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spy_cat',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exp_years', sa.Integer(), nullable=True),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('salary', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spy_cat_id'), 'spy_cat', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spy_cat_id'), table_name='spy_cat')
    op.drop_table('spy_cat')
    # ### end Alembic commands ###
