"""create_mission_table

Revision ID: f6a3917cd011
Revises: ed67296b7b62
Create Date: 2025-08-30 16:04:15.507235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6a3917cd011'
down_revision: Union[str, Sequence[str], None] = 'ed67296b7b62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('target',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_id'), 'target', ['id'], unique=True)
    op.create_table('mission',
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['spy_cat.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mission_id'), 'mission', ['id'], unique=True)
    op.create_table('target_note',
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_note_id'), 'target_note', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_note_id'), table_name='target_note')
    op.drop_table('target_note')
    op.drop_index(op.f('ix_mission_id'), table_name='mission')
    op.drop_table('mission')
    op.drop_index(op.f('ix_target_id'), table_name='target')
    op.drop_table('target')
    # ### end Alembic commands ###
